### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by Vogel612** [Vincentyification/JavaBot#30]
Since I wish to add a simple license to the testclient, it would be awesome if a definite license could be added here.

**Comment by Zomis** [comment]
Yes, please add a License to this. I am interested in using what you are making here for a [SE chatbot that informs about github activity](https://github.com/Zomis/GithubHookSEChatService).

I personally like the Simplified BSD or MIT licenses.

Although I should note: I am not interested in making any money whatsoever from what you're doing here. But at the same time, I also don't want to be enforced my code under GPL - which I am enforced to do if your code is GPL.

**Comment by Vogel612** [comment]
@Zomis Please share your thoughs on [ASL 2.0](http://www.apache.org/licenses/LICENSE-2.0). Most importantly the following section taken from the license text:

> 4 Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

> a) You must give any other recipients of the Work or Derivative Works a copy of this License; and
b) You must cause any modified files to carry prominent notices stating that You changed the files; and
c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
d) If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. 

> You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

To me this sounds like this would suit you better?

**Comment by Zomis** [comment]
The Apache License is perfectly acceptable for me, yes!

**Comment by Vincentyification** [comment]
Actually, I was going to use the MIT open source license, but eh.
@Vogel612: Do you prefer ASL (2.0)?

**Comment by Vogel612** [comment]
@Vincentyification both are fine by me. It'd be easier to use the ASL since you don't have to include a license header to every file (IIUC).
