### ISSUE TITLE
Avoid System.exit

### ISSUE THREAD

**Issue by Zomis** [Vincentyification/JavaBot#34]
Even though this question is about Swing, it applies here too: http://stackoverflow.com/a/3281935/1310566

As I plan on incorporating this in a web-based application, using `System.exit` would be devastating for me. Using System.exit is a mean way of terminating applications. Throw exceptions and/or interrupt threads instead.

**Comment by Vincentyification** [comment]
I agree. I wonder why it's there. It really needs a soft exit, the force termination should be done by containers.

**Comment by Vogel612** [comment]
I'm currently checking whether we can go through all threads with a poison pill to shut everything down orderly. I *fear* that might not be the case though. Let me investigate a bit more
