### ISSUE TITLE
Cleaning up `AbstractBot`

### ISSUE THREAD

**Issue by Zomis** [Vincentyification/JavaBot#39]
There are currently two `Executor`s in the `AbstractBot` class.

    protected final ScheduledExecutorService   executor         = Executors.newSingleThreadScheduledExecutor();
    protected final ExecutorService            processingThread = Executors.newSingleThreadExecutor();

One of them (`executor`) is shutdown inside the `finalize` method, **which is [a bad](http://stackoverflow.com/questions/2506488/when-is-the-finalize-method-called-in-java) [idea](http://stackoverflow.com/questions/18821753/java-finalize-method-use) to [rely on](http://stackoverflow.com/questions/12030641/how-to-ensure-finalize-is-always-called-thinking-in-java-exercise)**

The other one, `processingThread` is never shutdown at all, which makes a process running the JavaBot continue running because there is one or more threads that hasn't shutdown completely.

**Comment by Vogel612** [comment]
Should be fixed in following commit: https://github.com/Vogel612/JavaBot/commit/043ab5521fb715f42baf8597c227e105adbb3ec7 already ;)

The branch needs some more simmering, but the next PR I open will include a fix for this

**Comment by Zomis** [comment]
There is a `shutdown()` method in `DefaultBot`, but it is never called from anywhere - and it only shuts down one of the executors (the same one that is shutdown in the finalize method). Perhaps consider adding a `void shutdown()` method to the ChatWorker interface? Either way, make sure that the executors are shutdown. (Don't use the `finalize` method!)

**Comment by Vincentyification** [comment]
Thanks!
